### ISSUE TITLE
Library to script conversion possible?

### ISSUE THREAD

**Issue by paulochf** [mwilliamson/stickytape#10]
I just tried to use stickytape upon [better-exceptions](https://github.com/Qix-/better-exceptions) library, but I couldn't figure out what I should use as the "scripts/blah" parameter. Everything I tried resulted in errors.

Can I get some help? We could even enhance the readme after that.

Thanks!

**Comment by mwilliamson** [comment]
stickytape only works on scripts, but better-exceptions looks like a library. Could you explain a bit more about what your use-case is?

**Comment by paulochf** [comment]
I was wondering if I could transform a library into a single file script in order to get the resulting script and run into a Jupyter notebook's cell.

At least that's what I understood I could get with stickytape. Pardon me if I got it wrong.

**Comment by mwilliamson** [comment]
If I've understood your use-case correctly, I don't think stickytape supports what you're looking for: it converts a Python script with imports into a single-file Python script, whereas it looks like you want to convert a library (rather than a script).

**Comment by paulochf** [comment]
Right, no problem! Thanks for your time!
