### ISSUE TITLE
from __future__ import unicode_literals

### ISSUE THREAD

**Issue by lborgman** [mwilliamson/stickytape#21]
I get this error as a part of the problems in https://github.com/mwilliamson/stickytape/issues/20. I think it is better to have this as a separate issue.

 from __future__ import unicode_literals
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file

**Comment by mwilliamson** [comment]
If you're on Python 3, importing unicode_literals has no effect, so I'd suggest just getting rid of the import.

If you're on Python 2, I'd suggest using Python 3!

**Comment by lborgman** [comment]
The python code is not mine. It is from youtube-dl. I guess they have reasons not to remove the import yet.

May I suggest that you just comment those lines out when you produce the output code with stickytape? (I am not sure, but I think there are quite a few of those lines in youtube-dl.)

**Comment by mwilliamson** [comment]
Based on the code you posted, the issue is the import in the script you write, not in the modules that are imported (which, if memory serves, are copied verbatim, so should still have any future imports at the top).

**Comment by lborgman** [comment]
Thanks. I have no idea what I am doing wrong there. Can you please tell me?

**Comment by mwilliamson** [comment]
Make sure you're using Python 3, and delete the line:

```
from __future__ import unicode_literals
```

**Comment by lborgman** [comment]
I just did that. It did not work. The error is essentially the same as before:

"# python b.py
Traceback (most recent call last):
  File "/tmp/tmpnaxiw3gz/youtube_dl/extractor/__init__.py", line 4, in <module>
    from __future__ import unicode_literals
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "b.py", line 1640, in <module>
    import youtube_dl
  File "/tmp/tmpnaxiw3gz/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/tmp/tmpnaxiw3gz/youtube_dl/extractor/__init__.py", line 9, in <module>
    import io
  File "/tmp/tmpnaxiw3gz/youtube_dl/extractor/extractors.py", line 4, in <module>
ModuleNotFoundError: No module named 'youtube_dl.extractor.abc'"

**Comment by mwilliamson** [comment]
That's a different error from the original error. The original error is:

```
 from __future__ import unicode_literals
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

The new error is:

```
ModuleNotFoundError: No module named 'youtube_dl.extractor.abc'"
```

**Comment by lborgman** [comment]
Eh, sorry. Wrong issue. I thought you were commenting on the main issue (20) that I reported.

**Comment by lborgman** [comment]
Perhaps I should say that this issue is not a fatal blocking issue for me. Since you mentioned that the line does not do anything useful in python3 I can just postprocess the output. But anyway it would be very convenient if you did that processing in stickytape (so other people do not stumble on this issue if they try stickytape).

However issue 20 is a fatal blocking issue for me.

**Comment by lborgman** [comment]
@mwilliamson 
I guess you fixed this issue too? I do not see it any more.

**Comment by mwilliamson** [comment]
Nope, no change, you still shouldn't put future imports in the script.

**Comment by lborgman** [comment]
Oh, thanks, I see. I copied it from __main__.py and commented it out. I forgot I did that. And I thought there were more of those in the youtube-dl code since it appeared way down in the stickytape output. 

Then I close this.
