### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 83853-83854

### ISSUE THREAD

**Issue by lborgman** [mwilliamson/stickytape#25]
Using stickytape on my example in issue https://github.com/mwilliamson/stickytape/issues/20 now works excellent in the Ubuntu subsystem (20-21) on Windows 10.

However if I try to use the python file produced there directly in Window 10 (cmd shell) I get the error in the subject line.

**Comment by mwilliamson** [comment]
Could you provide the entire stack trace for the error?

**Comment by lborgman** [comment]
I could not redirect the python output in cmd.exe for some strange reason. This is from PowerShell instead. I think it is the same. (2>&1)

[temp.txt](https://github.com/mwilliamson/stickytape/files/5896245/temp.txt)

**Comment by mwilliamson** [comment]
Looks like an encoding issue when the modules get written out. I've just uploaded 0.2.1, which hopefully fixes the issue.

**Comment by lborgman** [comment]
Thanks, but I still get the same error. As before it works in the Ubuntu subsystem, but when testing the same output file in Windows cmd shell I still get the UnicodeEncodeError.

The traceback in cmd shell is exactly the same as before.

**Comment by mwilliamson** [comment]
Are you sure you're using the latest version of stickytape? The stack trace you posted before showed an encoding error when writing the contents of the module, but the contents of the module should now be byte strings (and therefore encoding shouldn't be a concern). Could you post the output generated by stickytape?

**Comment by mwilliamson** [comment]
If the stack trace is exactly the same, then I don't think you've generated the output file using the latest version of stickytape, since the `contents` argument should be a byte string, whereas the stack trace shows the argument being a (Unicode) string.

**Comment by lborgman** [comment]
I was just going to say I am not sure about that. I might have made some mistake when upgrading since I am not used to python. However I can't find any version info (except from "pip install stickytape"). 

I normally expect version info from something like "stickytape --version". And I also expect it in the stickytape output file.

Could you perhaps add such info?

**Comment by mwilliamson** [comment]
From the [docs for pip install](https://pip.pypa.io/en/stable/reference/pip_install/):

> Note that `pip install` prefers to leave the installed version as-is unless `--upgrade` is specified.

So if you already have stickytape installed, you'll need to pass `--upgrade` to install the latest version.

**Comment by lborgman** [comment]
Thanks, yes I know that. And I have the latest version installed. However I do not know exactly how old versions are handled. Maybe they are still around?

Hm, I just checked with "sudo python -m pip list" vs "python -m pip list". The old version is still there in the second case. (It should be very good if I could get the version directly from stickytape.)

**Comment by lborgman** [comment]
Ah, the output file (produced in Ubuntu subsystem) works in cmd shell! 

(I did "python -m pip uninstall stickytape". And exited the Ubuntu subsystem and entered it again.)

**Comment by lborgman** [comment]
It also works now to do everything in Windows 10 cmd shell.

**Comment by lborgman** [comment]
And the output file make in cmd shell works in the Ubuntu subsystem.

Many thanks for fixing this.

**Comment by mwilliamson** [comment]
I'm glad you got it working.
