### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\xff'

### ISSUE THREAD

**Issue by ishandutta2007** [mwilliamson/stickytape#27]
I am following the doc to get started.
Code:
```
pip install stickytape
stickytape .\myscript.py --add-python-path . > singlefilescript.py
python \.singlefilescript.py

```
Error:

```
  File ".\singlefilescript.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xff' in file .\single.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

my python version is 3.7.2

**Comment by mwilliamson** [comment]
Firstly, you almost certainly would be better off using something other than stickytape, such as zipapp or PyInstaller.

Secondly, to debug the issue (if you still want to use stickytape), could you post reproduction steps for a minimal example?
