### ISSUE TITLE
Explicitly add modules inline

### ISSUE THREAD

**Issue by tolgaerdonmez** [mwilliamson/stickytape#31]
Is there an adjustment that can be made to remove local imports from the file.
I want the imported local python codes embedded in the code without import statements.
I'm trying to run my code in firebase functions and it won't accept local imports rn. That's why I'm trying to merge my codebase into one main.py file with no local imports.

**Comment by mwilliamson** [comment]
Doing so is considerably trickier than the current approach since it would require some sort of transformation of each module to support being in the same file as other modules (for instance, to avoid name collisions). Unfortunately, I think it's unlikely that stickytape is going to support this.
