### ISSUE TITLE
Wrong directory separator on windows

### ISSUE THREAD

**Issue by dinnymate** [mwilliamson/stickytape#4]
` __stickytape_write_module('''path\\to\\Module.py''',....`

That's the code being generated on Windows. It fails both on windows and linux. If i manually change them to / it works everywhere.

Could you fix that please?

**Comment by mwilliamson** [comment]
`posixpath` is now used to generate module paths, so this hopefully fixed now. Unfortunately, I don't have a Windows machine to test on right now, so feel free to shout if the issue remains.
