### ISSUE TITLE
when i exec a cmpiled file in a cmpiled file ,raise NameError: global name '__stickytape_working_dir' is not defined

### ISSUE THREAD

**Issue by yongliangliu** [mwilliamson/stickytape#9]
such as 
i use stickytape A project to a sigle file named A, and stickytaped B project into a sigle file named B,

when i exec(B) in A raise NameError: global name '__stickytape_working_dir' is not defined

could you tell me hao to deal with it?

**Comment by mwilliamson** [comment]
Could you provide the code?

**Comment by mralves** [comment]
I am experiencing the same problem. Here is a example that raises this error:

 * module.py
```python
def say(s):
    print(s)
```

* minimal.py
```python
from module import say

say('Hello World!')
```

* exec.py
```python
with open('single.py') as s:
    source = s.read()
compiled = compile(source, '<string>', 'exec')
exec_locals = locals().copy()
exec_globals = globals().copy()
exec(compiled, exec_globals, exec_locals)
```

Running these:
```bash
$ stickytape minimal.py --add-python-path . > single.py
$ python exec.py
```

Raises this exception:
```
Traceback (most recent call last):
  File "exec.py", line 6, in <module>
    exec(compiled, exec_globals, exec_locals)
  File "<string>", line 38, in <module>
  File "<string>", line 29, in __stickytape_write_module
  File "<string>", line 22, in make_package
NameError: name '__stickytape_working_dir' is not defined
```

If I change:
```python
exec_locals = locals().copy()
exec_globals = globals().copy()
```
To:
```python
exec_locals = locals()
exec_globals = globals()
```
The problem does not occur anymore.
Version: 0.1.14

**Comment by mwilliamson** [comment]
`locals()` and `globals()` are the same at the module level (running `print(globals() is locals())` should print `True`). Therefore, when you call `exec()`, you should be passing the same value for globals and locals, rather than two separate dictionaries. In other words, you should change `exec.py` to:

```
with open('single.py') as s:
    source = s.read()
compiled = compile(source, '<string>', 'exec')
exec_globals = globals().copy()
exec(compiled, exec_globals)
```

**Comment by mralves** [comment]
Thanks! I did not know that!
